### ISSUE TITLE
2048-ai

### ISSUE THREAD

**Issue by Askold1989** [nneonneo/2048-ai#65] opened 2020-05-19 14:29 UTC
Greetings Dear !! I would like to ask about your 2048-ai, you are a genius and everything works perfectly, but your bot does not want to be enabled on a certain site. And outputs this text :
 
$ python 2048.py
Select a page to attach to:
1) \u0427\u0438\u0441\u043b\u043e\u043c\u0430\u043d\u0438\u044f:2048
2) nneonneo (Robert Xiao) \xb7 GitHub
Selection? 1
Traceback (most recent call last):
  File "2048.py", line 154, in <module>
    exit(main(sys.argv[1:]))
  File "2048.py", line 150, in main
    play_game(gamectrl)
  File "2048.py", line 96, in play_game
    board = gamectrl.get_board()
  File "/home/Михаил/gamectrl.py", line 89, in get_board
    grid = json.loads(self.execute('JSON.stringify(GameManager._instance.grid)'))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
 
What can I do to fix it and it worked on this site  . I'm just not good at it, but the bot is more needed than ever. I hope You will have time to respond and correct. Thank you in advance!!

**Comment by nneonneo** [comment] 2020-05-19 21:09
Hello,

This is a duplicate of #63. As I've mentioned in that thread, the "spasibosb" 2048 game is not using the same implementation as the original 2048 game, so it cannot be used with this bot.

**Closed by nneonneo** 2020-05-19 21:09 UTC
